export const WEBVIEW_EVENT_TYPE = {
  ROUTER_EVENT: "ROUTER_EVENT",
  NAV_BACK: "NAV_BACK",
  CLICK: "CLICK_EVENT",
  SEARCH_SUBMIT: "SEARCH_SUBMIT",
  SOCIAL_LOGIN: "SOCIAL_LOGIN",
  OPEN_EXTERNAL_LINK: "OPEN_EXTERNAL_LINK",
  HAPTIC_FEEDBACK: "HAPTIC_FEEDBACK",
  REQUEST_PERMISSION_AGAIN: "REQUEST_PERMISSION_AGAIN",
  OPEN_SETTINGS: "OPEN_SETTINGS",
  WEB_READY_FOR_MESSAGES: "WEB_READY_FOR_MESSAGES",
} as const;

export type WebviewEvent = keyof typeof WEBVIEW_EVENT_TYPE;
