export const DEFAULT_VALUE = {
  title: "",
  genre: "",
  address: "",
  age: "",
  style: [] as string[],
  detailAddress: "",
  openTime: "",
  websiteLink: "",
  condition: [] as string[],
  description: "",
  startDate: "",
  endDate: "",
  imgList: [] as string[],
  isFee: false,
  isPet: false,
  isReservation: false,
  isParking: false,
};
