name: Build and Deploy Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Get env from github action secret
        run: |
          touch ./.env.local

          echo "${{ secrets.DEV_ENV }}" > ./.env.local

      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-nextjs-server .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-nextjs-server:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.DEV_SERVER_HOST }}
          PW: ${{ secrets.DEV_SERVER_PW }}
          USER: ${{ secrets.DEV_SERVER_USER }}
        run: |
          sshpass -p "$PW" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-nextjs-server:latest
            docker stop ${{ secrets.DEV_SERVER_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DEV_SERVER_CONTAINER_NAME }} || true
            ls $ENV_FILE_PATH
            
            docker run -d -p 4000:3000 --name ${{ secrets.DEV_SERVER_CONTAINER_NAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-nextjs-server:latest
          EOF
